# Generated by Django 4.2.3 on 2023-08-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='verification'),
        ),
    ]
