# Generated by Django 4.2.3 on 2023-08-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification',
        ),
        migrations.AddField(
            model_name='user',
            name='register_uuid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='register_uuid'),
        ),
    ]
