# Generated by Django 4.2.3 on 2023-07-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_заголовок_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]
