# Generated by Django 4.2.3 on 2023-07-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category_description', models.CharField(max_length=1000, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('product_description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Фотот товара')),
                ('product_price', models.IntegerField(default=0, verbose_name='Наименование')),
                ('product_date_creation', models.DateTimeField(auto_now_add=True)),
                ('product_last_change', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('product_name',),
            },
        ),
    ]
