# Generated by Django 4.2.3 on 2023-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Фотот товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
    ]
