# Generated by Django 4.2.3 on 2023-08-03 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_vers', models.PositiveIntegerField(default=0, verbose_name='Номер версии')),
                ('name', models.CharField(max_length=250, verbose_name='Название версии')),
                ('is_active', models.BinaryField(default=True, verbose_name='Активная версия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
