# Generated by Django 4.2.3 on 2023-08-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
        migrations.RemoveField(
            model_name='version',
            name='is_active',
        ),
    ]
