# Generated by Django 4.2.3 on 2023-08-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_version_options_remove_version_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная версия'),
        ),
    ]
